# Generated by Django 3.0.4 on 2021-05-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210514_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hello.Friend'),
        ),
    ]
